markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables:
  - toc:
      baselevel: 2
      permalink: false

nav:
  - "index.md"
  - "Conference Chair":
      - "conference_chair/checklist.md"
  - "A/V":
      - "av/checklist.md"
  - "Communications":
      - "communications/checklist.md"
      - "communications/communications.md"
      - "communications/mailing_lists.md"
      - "communications/remarks.md"
  - "Community":
      - "community/checklist.md"
      - "community/visas.md"
      - "community/orientation.md"
  - "Conduct":
      - "conduct/checklist.md"
      - "conduct/conduct.md"
  - "Contribution Sprints":
      - "contribution_sprints/checklist.md"
  - "Drafts":
      - "drafts/coc_about.md"
      - "drafts/coc_complaint.md"
      - "drafts/coc_violation.md"
      - "drafts/drafts.md"
      - "drafts/email-tutorials-faqs.md"
      - "drafts/finaid_accepted.md"
      - "drafts/finaid_rejected.md"
      - "drafts/finaid_submitted.md"
      - "drafts/recruiting.md"
      - "drafts/talk_accepted.md"
      - "drafts/talk_rejected.md"
      - "drafts/talk_submitted.md"
      - "drafts/volunteer-info-email.md"
      - "drafts/volunteer.md"
      - "drafts/why-to-attend.md"
  - "Experience":
      - "experience/bathroom-baskets.md"
      - "experience/experience.md"
      - "experience/registration.md"
      - "experience/special_events.md"
      - "experience/visas.md"
      - "experience/volunteers.md"
  - "Health and Safety":
      - "health_and_safety/checklist.md"
  - "Inclusion":
      - "inclusion/checklist.md"
      - "inclusion/childcare.md"
      - "inclusion/inclusion.md"
  - "Lightning Talks":
      - "lightning_talks/checklist.md"
  - "Logistics":
      - "logistics/av.md"
      - "logistics/budget.md"
      - "logistics/design_website_checklist.md"
      - "logistics/logistics.md"
      - "logistics/organizers.md"
      - "logistics/photographer.md"
      - "logistics/post_conference.md"
      - "logistics/schedule.md"
      - "logistics/swag.md"
      - "logistics/tickets.md"
      - "logistics/timeline.md"
      - "logistics/venue.md"
      - "logistics/venue_checklist.md"
      - "logistics/website.md"
  - "Marketing":
      - "marketing/checklist.md"
  - "Online Committee":
      - "online_committee/checklist.md"
  - "Opportunity Grants":
      - "opportunity_grants/checklist.md"
      - "opportunity_grants/opportunity_grants.md"
  - "Program and Schedule":
      - "program_and_schedule/checklist.md"
      - "program_and_schedule/example_schedule.md"
      - "program_and_schedule/lightning_talks.md"
      - "program_and_schedule/orientation.md"
      - "program_and_schedule/program.md"
      - "program_and_schedule/sprints.md"
      - "program_and_schedule/sprints_checklist.md"
      - "program_and_schedule/timeline.md"
  - "Social Events":
      - "social_events/checklist.md"
  - "Sponsors":
      - "sponsors/checklist.md"
      - "sponsors/sponsors.md"
  - "Swag":
      - "swag/checklist.md"
  - "Tickets":
      - "tickets/checklist.md"
  - "Venue":
      - "venue/checklist.md"
  - "Volunteer Team":
      - "volunteer_team/checklist.md"
  - "Website":
      - "website/checklist.md"
plugins:
  - search
repo_url: https://github.com/djangocon/djangocon-us-docs
site_name: DjangoCon US Docs
theme:
  name: material
