[project]
name = "djangocon-us-docs"
version = "2026.1"
description = "DjangoCon US organizer documentation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs",
    "mkdocs-material",
]
